# -*- coding: UTF-8 -*-

"""
@Project ：flask_frame 
@File    ：abstract_system_config.py
@IDE     ：PyCharm 
@Author  ：Ethan
@Date    ：2024/5/21 22:14 
"""

from flask_frame.util.singleton import Singleton


class AbstractSystemConfig(metaclass=Singleton):
    # for debug
    ETCD_REFRESH_INTERVAL = 60

    # hook packages
    MANAGER_MODULE_NAME = 'manager'

    MODEL_MODULE_NAME = 'model'
    HBASE_MODEL_MODULE_NAME = 'model.hbase_model'
    MYSQL_MODEL_MODULE_NAME = 'model.mysql_model'
    MONGO_MODEL_MODULE_NAME = 'model.mongo_model'
    DATA_MODEL_MODULE_NAME = 'model.data_model'

    CELERY_TASK_MODULE_NAME = 'task.celery_task'
    CELERY_EXTERNAL_TASK_MODULE_NAME = 'task.celery_external_task'
    CELERY_BEAT_TASK_MODULE = 'task.celery_beat_task'
    CYCLIC_TASK_MODULE_NAME = 'task.cyclic_task'
    INSTANCE_TASK_MODULE_NAME = 'task.instance_task'

    TEST_CASE_MODULE_NAME = 'test_case'
    TEST_MAIN_MODULE_NAME = 'test_main'

    # hook module
    SETTING_MODULE_NAME = 'setting'
    INITIALIZER_MODULE_NAME = 'initializer'
    GLOBALS_MODULE_NAME = 'globals'
    CONST_MODULE_NAME = 'const'

    # hook module file
    SETTING_MODULE_FILE = 'setting.py'
    INITIALIZER_MODULE_FILE = 'initializer.py'
    GLOBALS_MODULE_FILE = 'globals.py'
    CONST_MODULE_FILE = 'const.py'

    # files
    LOGGER_CONFIG_FILE = 'logging.yaml'
    BACKUP_DIR = '../data/backup'
    CONFIG_FILE = 'config.yaml'
    CELERY_LOG_FILE = '../data/logs/celery.log'

    # celery serialize type
    CELERY_SERIALIZER_NAME = 'yg_json'

    # env
    LOGGER_CONFIG_ENV_KEY = 'LOG_CFG'
    ETCD_HOST_ENV_KEY = 'ETCD_SERVICE_SERVICE_HOST'
    ETCD_PORT_ENV_KEY = 'ETCD_SERVICE_SERVICE_PORT'
    DEBUG_MODE_ENV_KEY = 'DEBUG_MODE'

    # setting key
    CELERY_BROKER_URL_SETTING_KEY = 'BROKER_URL'
    CELERY_BACKEND_URL_SETTING_KEY = 'BACKEND_URL'
    CELERY_PACKAGE_UTIL_TIMEOUT_SETTING_KEY = 'CELERY_PACKAGE_UTIL_TIMEOUT'
    CELERY_MAX_CONCURRENCY_SETTING_KEY = 'CELERY_MAX_CONCURRENCY'

    ALARM_CELERY_TASK_BROKER_SETTING_KEY = 'ALARM_CELERY_TASK_BROKER'
    ALARM_CELERY_TASK_NAME_SETTING_KEY = 'ALARM_CELERY_TASK_NAME'
    ALARM_SERVICE_URL_SETTING_KEY = 'ALARM_SERVICE_URL'

    HBASE_HOST_SETTING_KEY = 'HBASE_HOST'
    HBASE_PORT_SETTING_KEY = 'HBASE_PORT'
    HBASE_POOL_SIZE_SETTING_KEY = 'HBASE_POOL_SIZE'
    HBASE_TIMEOUT_SETTING_KEY = 'HBASE_TIMEOUT'

    MYSQL_URL_SETTING_KEY = 'MYSQL_URL'
    MYSQL_POOL_SIZE_SETTING_KEY = 'MYSQL_POOL_SIZE'
    MYSQL_MAX_OVERFLOW_SETTING_KEY = 'MYSQL_MAX_OVERFLOW'
    MYSQL_POOL_RECYCLE_SETTING_KEY = 'MYSQL_POOL_RECYCLE'

    REDIS_HOST_SETTING_KEY = 'REDIS_HOST'
    REDIS_PORT_SETTING_KEY = 'REDIS_PORT'
    REDIS_PASSWORD_SETTING_KEY = 'REDIS_PASSWORD'
    REDIS_DB_SETTING_KEY = 'REDIS_DB'
    REDIS_DEFAULT_EXPIRE_SETTING_KEY = 'REDIS_DEFAULT_EXPIRE'

    MONGO_HOST_SETTING_KEY = 'MONGO_HOST'
    MONGO_PORT_SETTING_KEY = 'MONGO_PORT'
    MONGO_USERNAME_SETTING_KEY = 'MONGO_USERNAME'
    MONGO_PASSWORD_SETTING_KEY = 'MONGO_PASSWORD'
    MONGO_MAX_CONNECTION_POOL_SIZE_SETTING_KEY = 'MONGO_MAX_CONNECTION_POOL_SIZE'

    RABBITMQ_URL_SETTING_KEY = 'RABBITMQ_URL'

    TORNADO_PROC_NUM_SETTING_KEY = 'TORNADO_PROC_NUM'
    LISTEN_PORT_SETTING_KEY = 'LISTEN_PORT'

    PERMISSION_URL_SETTING_KEY = 'PERMISSION_URL'

    REGISTER_URL_SETTING_KEY = 'REGISTER_URL'

    ES_HOST_SETTING_KEY = 'ES_HOST'
    ES_HOSTS_SETTING_KEY = 'ES_HOSTS'
